### PR TITLE
fix: large legend shrinks chart in Explorer

### PR DESCRIPTION
**Pull request by cseas**
## Description

[Jira][1]

Fixes the bug for both Explorer screen and Custom Dashboard panels.

### Screenshots

|Before|
|:-----:|
| before |
|After|
| after |

### Testing
Test on [stage environment][2]

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

[1]: https://razorpay.atlassian.net/browse/OBSV-1108
[2]: https://hypertrace.concierge.stage.razorpay.in/explorer?time=1h&scope=spans&series=column:count(spans)&filter=serviceName_eq_api&filter=spanTags_ck_db.system&group=spanTags__db.statement&limit=10

### CODE REVIEW

**Comment by jaywalker21** [comment]
@cseas Does hovering over the overflowing text give out a tooltip showing the whole text? Just want to ensure that no one comes and raises an issue that they cannot differentiate when some legends have similar text in the beginning.

**Comment by cseas** [comment]
@jaywalker21 Tried to add `text-overflow: ellipsis;` but it doesn't seem to be working, not sure if d3 is messing up with the CSS here.

Screenshot 2022-11-11 at 12 56 27 PM

```css
/* cartesian-chart.components.scss */
.legend-text {
  max-width: 130px;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

So I instead wrote a method to add the ellipsis with JS. Seems to work fine.

Screenshot 2022-11-11 at 1 08 12 PM

> @cseas Does hovering over the overflowing text give out a tooltip showing the whole text?

Whole text is shown, yes. Screenshot above.

**Comment by cseas** [comment]
@Sunn-y-Arora @subintp Deployed the changes to [stage environment](https://hypertrace.concierge.stage.razorpay.in/explorer?time=1h&scope=spans&series=column:count(spans)&filter=serviceName_eq_api&filter=spanTags_ck_db.system&group=spanTags__db.statement&limit=10). Please check and approve if it looks good.

**Comment by jaywalker21** [comment]
So, not in favour of doing this on the JS side, if the CSS layer can handle it. Tried the following, seems to work. Can you check once?

image

I applied the following styles on the `span` which shows the text, it's class is `legend-text`.

```css
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  width: 200px;
```

**Comment by cseas** [comment]
> ```css
>   white-space: nowrap;
>   overflow: hidden;
>   text-overflow: ellipsis;
>   width: 200px;
> ```

Ah, looks like I was missing `overflow: hidden`. CSS works. Changes pushed. ✅

**Review by jaywalker21 — APPROVED** [review]
LGTM

**Pull request merged**
